// hw04/src/views/identity/Register.vue
<template>
    <div class="row">
        <div class="col-sm-1 col-md-3"></div>
        <div class="col-sm-10 col-md-6">
            <h4>Create a new account</h4>
            <hr />
            <div class="form-group">
                <label for="Input_Email">Email</label>
                <input
                    class="form-control"
                    type="email"
                    id="Input_Email"
                    v-model="email"
                />
                <br>
            </div>
            <div class="form-group">
                <label for="Input_Password">Password</label>
                <input
                    class="form-control"
                    type="password"
                    id="Input_Password"
                    v-model="password"
                />
                 <br>
            </div>
            <div class="form-group">
                <label for="Input_Firstname">Firstname</label>
                <input
                    class="form-control"
                    type="firstname"
                    id="Input_Firstname"
                    v-model="firstname"
                />
                <br>
            </div>
            <div class="form-group">
                <label for="Input_Lastname">Lastname</label>
                <input
                    class="form-control"
                    type="lastname"
                    id="Input_Lastname"
                    v-model="lastname"
                />
                <br>
            </div>
            <div class="form-group">
                <button
                    @click="registerClicked($event)"
                    type="submit"
                    class="btn btn-dark"
                >
                    Register
                </button>
            </div>
        </div>
        <div class="col-sm-1 col-md-3"></div>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";
import router from "vue-router";

@Options({
    components: {},
    props: {},
})
export default class Register extends Vue {
    email: string = "elmar";
    password: string = "Elmar123..";
    firstname: string = "el";
    lastname: string = "mar";

    async registerClicked(event: Event): Promise<void> {
        store
            .dispatch("register", { email: this.email, password: this.password, firstname: this.firstname, lastname: this.lastname })
            .then(() => {
                if (store.state.token != null) {
                    this.$router.push("/");
                }
            });
    }
}
</script>

// hw05/src/containers/identity/Register.tsx
import React, { useContext, useState } from "react";
import { Redirect } from "react-router";
import Alert, { EAlertClass } from "../../components/Alert";
import { AppContext } from "../../context/AppContext";
import { IdentityService } from "../../services/identity-service";

const Register = () => {
    const appState = useContext(AppContext);

    const [loginData, setLoginData] = useState({ email: "", password: "" , firstName: "", lastName: ""});
    const [alertMessage, setAlertMessage] = useState("");

    const registerClicked = async (e: Event) => {
        e.preventDefault();
        if (loginData.email === "" || loginData.password === "") {
            setAlertMessage("Empty email or password!");
        }
        setAlertMessage("");
        let response = await IdentityService.Login("Account/Register", loginData);
        if (!response.ok) {
            setAlertMessage(response.messages![0]);
        } else {
            setAlertMessage("");
            appState.setAuthInfo(response.data!.token, response.data!.firstName, response.data!.lastName);
        }
    };

    return (
        <>
            {appState.token !== null ? <Redirect to="/" /> : null}
            <form onSubmit={(e) => registerClicked(e.nativeEvent)}>
                <div className="row">
                    <div className="col-sm-1 col-md-3"></div>
                    <div className="col-sm-10 col-md-6">
                    <h4>Create a new account</h4>
                        <section>
                            <hr />
                            <Alert show={alertMessage !== ""} message={alertMessage} alertClass={EAlertClass.Danger} />
                            <div className="form-group">
                                <label htmlFor="Input_Email">Email</label>
                                <input
                                    value={loginData.email}
                                    onChange={(e) => setLoginData({ ...loginData, email: e.target.value })}
                                    className="form-control"
                                    type="email"
                                    id="Input_Email"
                                    name="Input.Email"
                                    placeholder="user@example.com"
                                />
                            </div>
                            <br/>
                            <div className="form-group">
                                <label htmlFor="Input_Password">Password</label>
                                <input
                                    value={loginData.password}
                                    onChange={(e) => setLoginData({ ...loginData, password: e.target.value })}
                                    className="form-control"
                                    type="password"
                                    id="Input_Password"
                                    name="Input.Password"
                                    placeholder="password"
                                />
                            </div>
                            <br/>
                            <div className="form-group">
                                <label htmlFor="Input_Firstname">Firstname</label>
                                <input
                                    value={loginData.firstName}
                                    onChange={(e) => setLoginData({ ...loginData, firstName: e.target.value })}
                                    className="form-control"
                                    type="firstname"
                                    id="Input_Firstname"
                                    name="Input.Firstname"
                                    placeholder="firstname"
                                />
                            </div>
                            <br/>
                            <div className="form-group">
                                <label htmlFor="Input_Lastname">Lastname</label>
                                <input
                                    value={loginData.lastName}
                                    onChange={(e) => setLoginData({ ...loginData, lastName: e.target.value })}
                                    className="form-control"
                                    type="lastname"
                                    id="Input_Lastname"
                                    name="Input.Lastname"
                                    placeholder="lastname"
                                />
                            </div>
                            <br/>
                            <div className="form-group">
                                <button
                                    onClick={(e) => registerClicked(e.nativeEvent)}
                                    type="submit"
                                    className="btn btn-dark"
                                >
                                    Register
                                </button>
                            </div>
                        </section>
                    </div>
                </div>
            </form>
        </>
    );
};

export default Register;
